import = ["/Users/slavshik/.config/alacritty/themes/gruvbox_dark.yaml"]
live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGL Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002s"
key = "Backslash"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002W"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002S"
key = "T"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u0002e"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002)"
key = "LBracket"
mods = "Command|Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002("
key = "RBracket"
mods = "Command|Alt|Shift"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00035"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00036"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00037"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00038"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00039"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00030"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;6D"
key = "LBracket"
mods = "Command|Shift|Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;6C"
key = "RBracket"
mods = "Command|Shift|Alt"

[[keyboard.bindings]]
chars = " K"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = " MM"
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = " fi"
key = "Key1"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "gd"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "gcc"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "gb"
key = "Slash"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = " T"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = " o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = ">"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
chars = " lo"
key = "F7"
mods = "Command"

[[keyboard.bindings]]
chars = " ds"
key = "F12"
mods = "Command"

[[keyboard.bindings]]
chars = " lf"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = " FF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
 ee
"""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
_run
"""
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = """
_run_s
"""
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = " II"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = " ii"
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002["
key = "Semicolon"
mods = "Command"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.94
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 8
y = 16
