import = [
    "~/.config/alacritty/themes/gruvbox_dark.yaml",
    "~/.config/alacritty/keybindings.toml",
]
live_config_reload = true
working_directory = "None"

[window]
decorations = "Transparent"
padding = { x = 8, y = 30 }
dimensions = { columns = 110, lines = 30 }
opacity = 0.9
blur = true
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGL Nerd Font"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
