# \u0002 - ctrl+b (tmux prefix)
[keyboard]
bindings = [
    { key = "S", mods = "Command", chars = "\u001B:w\n" }, # save command
    { key = "W", mods = "Command", chars = "\u0002W" }, # !CLOSE TAB/vim/Terminal/etc
    { key = "N", mods = "Command|Shift", chars = "\u0002S" }, # new tmux session
    { key = "T", mods = "Command", chars = "\u0002c" }, # new tmux tab
    { key = "K", mods = "Command|Shift", chars = " K" }, # open lazygit
    { key = "Slash", mods = "Command", chars = "gcc" }, # comment line 
    { key = "Slash", mods = "Command|Alt", chars = "gb" }, # comment out block

    { key = "|", mods="Command|Shift", chars = "\u0002w" }, # tmux all sessions view
    { key = "{", mods="Command|Shift", chars = "\u0002p" }, # tmux previous session
    { key = "}", mods="Command|Shift", chars = "\u0002n" }, # tmux next session
    { key = "LBracket", mods = "Command", chars = "\u0002\u001B[D" }, # tmux left pane
    { key = "RBracket", mods = "Command", chars = "\u0002\u001B[C" }, # tmux right pane
    { key = "LBracket", mods = "Command|Alt|Shift", chars = "\u0002)" }, # tmux next session
    { key = "RBracket", mods = "Command|Alt|Shift", chars = "\u0002(" }, # tmux previous session
    { key = "T", mods = "Command|Shift", chars = "\u0002%" }, # tmux open new pane (vertical)
    { key = "!", mods = "Command|Shift", chars = " !@f" }, # open file in Finder

    { key = "LBracket", mods = "Command|Shift|Alt", chars = "\u0002\u001B[1;6D" },
    { key = "RBracket", mods = "Command|Shift|Alt", chars = "\u0002\u001B[1;6C" },

    { key = "E", mods = "Command", chars = " e" },
    { key = "E", mods = "Command|Shift", chars = "\u0002e" },
    { key = "M", mods = "Command|Shift", chars = " MM" },
    { key = "B", mods = "Command", chars = "gd" },
    { key = "P", mods = "Command|Shift", chars = " T" },
    { key = "O", mods = "Command", chars = " o" },
    { key = "O", mods = "Command|Shift", chars = " lf" }, # open lf browser
    { key = "Return", mods = "Alt", chars = ">" },
    { key = "Return", mods = "Alt|Shift", chars = "<" },
    { key = "D", mods = "Command", chars = "\u0002d" },
    { key = "R", mods = "Command", chars = "_run\n" },
    { key = "F", mods = "Command|Shift", chars = " FF" },
    { key = "I", mods = "Command", chars = " II" }, # npm_install script
    { key = "I", mods = "Command|Shift", chars = " ii" }, # yarnrun script
    { key = "K", mods = "Command", chars = "\u0002K" }, # session manager

    # -------------------------------------------------------------
    # 
    # 
    # -------------------------------------------------------------
    { key = "F1", mods = "Shift", chars = "\u001B[1;2P" },
    { key = "F2", mods = "Shift", chars = "\u001B[1;2Q" },
    { key = "F3", mods = "Shift", chars = "\u001B[1;2R" },
    { key = "F4", mods = "Shift", chars = "\u001B[1;2S" },
    { key = "F5", mods = "Shift", chars = "\u001B[15;2~" },
    { key = "F6", mods = "Shift", chars = "\u001B[17;2~" },
    { key = "F7", mods = "Shift", chars = "\u001B[18;2~" },
    { key = "F8", mods = "Shift", chars = "\u001B[19;2~" },
    { key = "F9", mods = "Shift", chars = "\u001B[20;2~" },
    { key = "F10", mods = "Shift", chars = "\u001B[21;2~" },
    { key = "F11", mods = "Shift", chars = "\u001B[23;2~" },
    { key = "F12", mods = "Shift", chars = "\u001B[24;2~" },
    { key = "F1", mods = "Control", chars = "\u001B[1;5P" },
    { key = "F2", mods = "Control", chars = "\u001B[1;5Q" },
    { key = "F3", mods = "Control", chars = "\u001B[1;5R" },
    { key = "F4", mods = "Control", chars = "\u001B[1;5S" },
    { key = "F5", mods = "Control", chars = "\u001B[15;5~" },
    { key = "F6", mods = "Control", chars = "\u001B[17;5~" },
    { key = "F7", mods = "Control", chars = "\u001B[18;5~" },
    { key = "F8", mods = "Control", chars = "\u001B[19;5~" },
    { key = "F9", mods = "Control", chars = "\u001B[20;5~" },
    { key = "F10", mods = "Control", chars = "\u001B[21;5~" },
    { key = "F11", mods = "Control", chars = "\u001B[23;5~" },
    { key = "F12", mods = "Control", chars = "\u001B[24;5~" },
    { key = "F1", mods = "Alt", chars = "\u001B[1;6P" },
    { key = "F2", mods = "Alt", chars = "\u001B[1;6Q" },
    { key = "F3", mods = "Alt", chars = "\u001B[1;6R" },
    { key = "F4", mods = "Alt", chars = "\u001B[1;6S" },
    { key = "F5", mods = "Alt", chars = "\u001B[15;6~" },
    { key = "F6", mods = "Alt", chars = "\u001B[17;6~" },
    { key = "F7", mods = "Alt", chars = "\u001B[18;6~" },
    { key = "F8", mods = "Alt", chars = "\u001B[19;6~" },
    { key = "F9", mods = "Alt", chars = "\u001B[20;6~" },
    { key = "F10", mods = "Alt", chars = "\u001B[21;6~" },
    { key = "F11", mods = "Alt", chars = "\u001B[23;6~" },
    { key = "F12", mods = "Alt", chars = "\u001B[24;6~" },
    { key = "F1", mods = "Super", chars = "\u001B[1;3P" },
    { key = "F2", mods = "Super", chars = "\u001B[1;3Q" },
    { key = "F3", mods = "Super", chars = "\u001B[1;3R" },
    { key = "F4", mods = "Super", chars = "\u001B[1;3S" },
    { key = "F5", mods = "Super", chars = "\u001B[15;3~" },
    { key = "F6", mods = "Super", chars = "\u001B[17;3~" },
    { key = "F7", mods = "Super", chars = "\u001B[18;3~" },
    { key = "F8", mods = "Super", chars = "\u001B[19;3~" },
    { key = "F9", mods = "Super", chars = "\u001B[20;3~" },
    { key = "F10", mods = "Super", chars = "\u001B[21;3~" },
    { key = "F11", mods = "Super", chars = "\u001B[23;3~" },
    { key = "F12", mods = "Super", chars = "\u001B[24;3~" },
    # ----------------------------------------------------
    { key = "Key1", mods = "Command", chars = "\u00021" },
    { key = "Key2", mods = "Command", chars = "\u00022" },
    { key = "Key3", mods = "Command", chars = "\u00023" },
    { key = "Key4", mods = "Command", chars = "\u00024" },
    { key = "Key5", mods = "Command", chars = "\u00035" },
    { key = "Key6", mods = "Command", chars = "\u00036" },
    { key = "Key7", mods = "Command", chars = "\u00037" },
    { key = "Key8", mods = "Command", chars = "\u00038" },
    { key = "Key9", mods = "Command", chars = "\u00039" },
    { key = "Key0", mods = "Command", chars = "\u00030" },
]

