# Font
font_family       MesloLGL Nerd Font Mono
font_size         14.0
macos_thicken_font          0.75
text_composition_strategy   1.7 30

# Window
hide_window_decorations    titlebar-only
window_padding_width       30 8
remember_window_size       no
initial_window_width       110c
initial_window_height      30c
background_opacity         0.9
background_blur            20
macos_option_as_alt        yes

# Cursor
cursor_shape               block
cursor_shape_unfocused     hollow

# Mouse
mouse_hide_wait            0
mouse_map middle release ungrabbed paste_from_selection

# Scrolling
scrollback_lines           10000
wheel_scroll_multiplier    3.0

# Selection
copy_on_select             no

# Bell
enable_audio_bell          no

# Shell integration plays nicely with tmux + zsh
shell_integration          enabled

include theme.conf
include keybindings.conf
