[[session]]
name = "⚙️ Dotfiles"
path = "~/.dotfiles"
startup_command = "lazygit"
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "🏠Home"
path = "~"

[[session]]
name = "🥥Ela" 
path = "~/Documents/Ela"
# startup_script = "~/.config/sesh/scripts/evo"

[[session]]
name = "🪴Evo"
path = "~/Documents/EVO/js-clients/"
startup_script = "~/.config/sesh/scripts/evo"

[[session]]
name = "🐶Diesel"
path = "~/Documents/Diesel/"

[[session]]
name = "💻Dev"
path = "~/Documents/dev/"
startup_command = "l"

[[session]]
name = "🖥 Desktop"
path = "~/Desktop/"
