bindkey -s ' lf' 'lfcd\n'
bindkey -s '^BW' 'exit\n'
bindkey -s '^BK' 'sesh connect $(sesh list -c | fzf)\n'
bindkey -s '^P' 'nvim .\n'
bindkey -s ' K' 'lg\n'
bindkey -s ' ee' '^R'
bindkey -s '^Be' 'nvim\n'
bindkey -s ' !@f' 'open -R .\n'
bindkey -s ' ii' 'yarnrun\n'
bindkey -s ' II' 'npm_install\n'
